# mysql连接池配置
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@39.98.176.209:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: dc
    password: dc
    druid:
      ##初始化连接数
      initialSize: 5
      ##最小空闲数
      minIdle: 5
      ##最大活动数
      maxActive: 20
      ##最大等待时间
      maxWait: 60000
      ##每60秒运行一次空闲连接回收器
      timeBetweenEvictionRunsMillis: 60000
      ##池中连接空闲时隔多久被回收
      minEvictableIdleTimeMillis: 30000
      ##验证使用的sql语句
      validationQuery: SELECT 1 FROM DUAL
      ##验证sql语句的超时时间
      validationQueryTimeout: 10000
      ##指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      ##借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      testOnReturn: false
      ##连接池使用预处理语句
      poolPreparedStatements: true
      ##每个连接最大拥有多少PreparedStatement
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      useGlobalDataSourceStat: true
      ##连接泄露回收参数
      removeAbandoned: false
      filter:
        commons-log:
          enabled: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: null
        deny: null
#dubbo配置
dubbo:
  config:
    multiple: true
  application:
    name: digital-server
  registries:
    digital:
      address: localhost:2181
      protocol: zookeeper
      check: false
      id: gaism
    fms:
      #address: 192.168.1.98:2190
      #address: 192.168.5.233:2181
      #address: 192.168.5.34:2181
      address: 192.168.5.222:2181
      protocol: zookeeper
      check: false
      id: fms
    uums:
      address:  localhost:2181
      protocol: zookeeper
      check: false
      id: uums
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.greatmap.digital

logging:
  config: classpath:logback-dev.xml

sign:
  ca: HBCA
  hbca:
    http: http://221.232.224.75:8880/hbcaess/rest/
  sxca:
    http: http://117.32.132.78:19000/cloudsign/resource/rest/v1/shared/

wcf:
  wcfServer: 192.168.5.34:9090
  estatePrintUrl: /MapFunService/EstatePrint
  tempDirectory: C:/FTP/work/print
  relativePath: estate/documents/register

ftp:
  host: ftp://192.168.5.222:38333
  user: ftp
  psw: ftp
  http: http://192.168.5.34:18080/ftpdirectory



tempDirectory: C:/FTP/work/print

dex:
  dcPublicKey: A9UpigS3bMWtp+1YbjjJvsmE7Uz4FABMgruG4uApBqki
  dcPrivateKey: AKxdgJ9cOLlJ2WGs4w6GpcHw9TgmFTMKc+X8wmubzMYV
  systemCode: dcSyscode
  dexSenderPublicKeyUrl: http://wh.greatmap.com.cn:8013/dsp-register-server/dspRegisterService/proxyService/getSenderPublicSecret
  dexSenderIndustryCodeUrl: http://wh.greatmap.com.cn:8013/dsp-register-server/dspRegisterService/dockingSystemService/queryIndustryCodeAndAreaCodeBySystemCode
  dexPublicKeyUrl: http://wh.greatmap.com.cn:8013/dsp-register-server/dspRegisterService/proxyService/getReceiverPublicSecret
